controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    use_sim_time: False
    left_wheel_names: ["left_motor"]
    right_wheel_names: ["right_motor"]

    wheel_separation: 0.6
    wheel_radius: 0.13

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.112

    use_stamped_vel: False
    base_frame_id: "base_link"

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: False
#   ros__parameters:
#     extra_joints:
#       - LDS-01_secondary_motor
#       - LDS-01_main_motor
